package pkginstaller

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ScriptData holds the template data model for script generation.
type ScriptData struct {
	Identifier      string
	Name            string
	Version         string
	InstallPrefix   string   // e.g. /Library/MyTool/1.2.0
	Binaries        []string // auto-detected from files → bin/*
	HasManPages     bool
	ManPrefix       string   // e.g. /Library/MyTool/1.2.0/share/man
	HasConfig       bool
	ConfigDir       string   // e.g. /Library/MyTool/1.2.0/etc
	SymlinkBinaries bool
}

// detectBinaries scans file destinations for paths ending in bin/<name> where
// "bin" is the penultimate path component. Returns the basenames of detected binaries.
func detectBinaries(files map[string]string) []string {
	seen := make(map[string]bool)
	var binaries []string
	for _, dst := range files {
		dir, name := filepath.Split(strings.TrimSuffix(dst, "/"))
		if name == "" {
			continue
		}
		// Check that the parent directory is "bin"
		dir = strings.TrimSuffix(dir, "/")
		if filepath.Base(dir) == "bin" {
			if !seen[name] {
				seen[name] = true
				binaries = append(binaries, name)
			}
		}
	}
	return binaries
}

// detectManPages returns true if any file destination contains share/man.
func detectManPages(files map[string]string) bool {
	for _, dst := range files {
		if strings.Contains(dst, "share/man") {
			return true
		}
	}
	return false
}

// detectConfig returns true if any file destination contains etc/.
func detectConfig(files map[string]string) bool {
	for _, dst := range files {
		if strings.Contains(dst, "/etc/") || strings.HasSuffix(dst, "/etc") {
			return true
		}
	}
	return false
}

const postinstallTemplate = `#!/bin/bash
set -e

NAME="{{.Name}}"
PREFIX="{{.InstallPrefix}}"

# Write paths.d entry so binaries are in $PATH
mkdir -p /etc/paths.d
echo "${PREFIX}/bin" > "/etc/paths.d/${NAME}"
{{if .HasManPages}}
# Write manpaths.d entry for man pages
mkdir -p /etc/manpaths.d
echo "{{.ManPrefix}}" > "/etc/manpaths.d/${NAME}"
{{end}}
{{- if .SymlinkBinaries}}
# Create symlinks in /usr/local/bin
mkdir -p /usr/local/bin
{{- range .Binaries}}
ln -sf "{{$.InstallPrefix}}/bin/{{.}}" "/usr/local/bin/{{.}}"
{{- end}}
{{end}}
exit 0
`

const postupgradeTemplate = `#!/bin/bash
set -e

NAME="{{.Name}}"
PREFIX="{{.InstallPrefix}}"

# Write paths.d entry so binaries are in $PATH
mkdir -p /etc/paths.d
echo "${PREFIX}/bin" > "/etc/paths.d/${NAME}"
{{if .HasManPages}}
# Write manpaths.d entry for man pages
mkdir -p /etc/manpaths.d
echo "{{.ManPrefix}}" > "/etc/manpaths.d/${NAME}"
{{end}}
{{- if .SymlinkBinaries}}
# Create symlinks in /usr/local/bin
mkdir -p /usr/local/bin
{{- range .Binaries}}
ln -sf "{{$.InstallPrefix}}/bin/{{.}}" "/usr/local/bin/{{.}}"
{{- end}}
{{end}}
# Restore backed-up config if present
{{- if .HasConfig}}
BACKUP_DIR="/tmp/bakepkg-upgrade-${NAME}"
if [ -d "${BACKUP_DIR}" ]; then
    cp -R "${BACKUP_DIR}/"* "{{.ConfigDir}}/" 2>/dev/null || true
    rm -rf "${BACKUP_DIR}"
fi
{{end}}
exit 0
`

const preupgradeTemplate = `#!/bin/bash
set -e

NAME="{{.Name}}"
{{- if .HasConfig}}

# Back up config files before upgrade
BACKUP_DIR="/tmp/bakepkg-upgrade-${NAME}"
rm -rf "${BACKUP_DIR}"
mkdir -p "${BACKUP_DIR}"
if [ -d "{{.ConfigDir}}" ]; then
    cp -R "{{.ConfigDir}}/"* "${BACKUP_DIR}/" 2>/dev/null || true
fi
{{end}}
exit 0
`

const uninstallTemplate = `#!/bin/bash
# macOS Package Uninstaller Script for {{.Name}}
# Generated by bakepkg

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

echo "Uninstalling {{.Identifier}}..."

# Remove paths.d entry
rm -f "/etc/paths.d/{{.Name}}"
{{if .HasManPages}}
# Remove manpaths.d entry
rm -f "/etc/manpaths.d/{{.Name}}"
{{end}}
{{- if .SymlinkBinaries}}
# Remove symlinks
{{- range .Binaries}}
rm -f "/usr/local/bin/{{.}}"
{{- end}}
{{end}}
# Remove installation directory
rm -rf "{{.InstallPrefix}}"

# Forget the package receipt
pkgutil --forget "{{.Identifier}}"

echo "Done."
exit 0
`

// generateScripts renders script templates and writes them to scriptsDir.
// It also writes an uninstall.sh into buildDir as part of the payload.
func generateScripts(opts Options, scriptsDir, buildDir string) error {
	prefix := fmt.Sprintf("%s/%s/%s", InstallLocationLibrary, opts.Name, opts.Version)

	data := ScriptData{
		Identifier:      opts.Identifier,
		Name:            opts.Name,
		Version:         opts.Version,
		InstallPrefix:   prefix,
		Binaries:        detectBinaries(opts.Files),
		HasManPages:     detectManPages(opts.Files),
		ManPrefix:       prefix + "/share/man",
		HasConfig:       detectConfig(opts.Files),
		ConfigDir:       prefix + "/etc",
		SymlinkBinaries: opts.SymlinkBinaries,
	}

	if err := os.MkdirAll(scriptsDir, 0755); err != nil {
		return fmt.Errorf("failed to create scripts dir: %w", err)
	}

	// Always generate postinstall
	if err := renderScript(postinstallTemplate, data, filepath.Join(scriptsDir, "postinstall")); err != nil {
		return fmt.Errorf("failed to generate postinstall: %w", err)
	}

	// Generate upgrade scripts if config is detected
	if data.HasConfig {
		if err := renderScript(preupgradeTemplate, data, filepath.Join(scriptsDir, "preupgrade")); err != nil {
			return fmt.Errorf("failed to generate preupgrade: %w", err)
		}
		if err := renderScript(postupgradeTemplate, data, filepath.Join(scriptsDir, "postupgrade")); err != nil {
			return fmt.Errorf("failed to generate postupgrade: %w", err)
		}
	}

	// Generate uninstall.sh in the build payload under bin/
	uninstallDir := filepath.Join(buildDir, opts.Name, opts.Version, "bin")
	if err := os.MkdirAll(uninstallDir, 0755); err != nil {
		return fmt.Errorf("failed to create uninstall dir: %w", err)
	}
	if err := renderScript(uninstallTemplate, data, filepath.Join(uninstallDir, "uninstall.sh")); err != nil {
		return fmt.Errorf("failed to generate uninstall.sh: %w", err)
	}

	return nil
}

func renderScript(tmplStr string, data ScriptData, path string) error {
	tmpl, err := template.New("script").Parse(tmplStr)
	if err != nil {
		return err
	}

	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, data)
}
